version: "3.8"

services:
  rustic-sketch:
    image: rafaelfiume/rustic-sketch:latest
    container_name: rustic-sketch
    ports:
      - "3030:3030"
    depends_on:
      - rustic-database

  rustic-database:
    image: postgres:16.2-bullseye
    container_name: rustic-postgres
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    environment:
      - POSTGRES_DB=rustic-sketch
      - POSTGRES_USER=rustic-sketch.dev
      - POSTGRES_PASSWORD=rustic-sketch.pw
    volumes:
      - rustic_postgres_data:/var/lib/postgresql/rustic/data # Persist the database data

volumes:
  rustic_postgres_data:
